@startuml(id=DWHBDevelopment-Container)
title DWH B Development - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam database<<22>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam database<<10>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
package "DWH B Development\n[Software System]" {
  database "==DWH database Development (Project B)\n<size:10>[Container: Database]</size>" <<22>> as 22
  database "==Repository database (Project B)\n<size:10>[Container: Database]</size>" <<10>> as 10
}
22 .[#707070].> 10 : "RepoObject correspond with extended properties"
10 .[#707070].> 22 : "Synonyms link to DWH System Views"
@enduml