@startuml(id=SystemLandscape)
title System Landscape for Customer

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam folder<<22>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<23>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<24>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<3>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<4>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam folder<<27>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<20>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
rectangle "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<23>> as 23
rectangle "==DataHandwerk Development\n<size:10>[Software System]</size>" <<24>> as 24
folder "==DataHandwerk git\n<size:10>[Software System]</size>\n\nCode of DataHandwerk in Version Control" <<27>> as 27
package "Customer" {
  rectangle "==DWH Developer\n<size:10>[Person]</size>\n\nDeveloper of some DWH" <<1>> as 1
  rectangle "==Deployment Team\n<size:10>[Person]</size>" <<2>> as 2
  rectangle "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<3>> as 3
  rectangle "==DWH B Development\n<size:10>[Software System]</size>" <<4>> as 4
  rectangle "==DWH B Production\n<size:10>[Software System]</size>" <<20>> as 20
  folder "==DWH B git\n<size:10>[Software System]</size>\n\nCode of Project B in Version Control (git, subversion, ...)" <<22>> as 22
}
23 .[#707070].> 24 : "uses for testing and development"
23 .[#707070].> 27 : "uses"
1 .[#707070].> 4 : "developes"
1 .[#707070].> 22 : "uses"
1 .[#707070].> 27 : "takes code or builds"
2 .[#707070].> 20 : "deployes on production system"
2 .[#707070].> 22 : "takes code or builds"
3 .[#707070].> 20 : "uses"
@enduml