@startuml(id=DataHandwerkDevelopment-Container)
title DataHandwerk Development - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam database<<26>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam database<<27>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
package "DataHandwerk Development\n[Software System]" {
  database "==DWH db (Project A)\n<size:10>[Container: Database]</size>" <<27>> as 27
  database "==Repository db (Project A)\n<size:10>[Container: Database]</size>" <<26>> as 26
}
@enduml