@startuml(id=DWHBProduction-Container)
title DWH B Production - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam database<<26>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<7>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<8>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
rectangle "==Deployment Team\n<size:10>[Person]</size>" <<7>> as 7
rectangle "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<8>> as 8
package "DWH B Production\n[Software System]" {
  database "==DWH database Production (Project B)\n<size:10>[Container: Database]</size>" <<26>> as 26
}
7 .[#707070].> 26 : "deployes on production system"
8 .[#707070].> 26 : "uses"
@enduml