@startuml(id=DataHandwerkDevelopment-SystemContext)
title DataHandwerk Development - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<24>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<25>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
rectangle "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<24>> as 24
rectangle "==DataHandwerk Development\n<size:10>[Software System]</size>" <<25>> as 25
24 .[#707070].> 25 : "uses for testing and development"
@enduml