@startuml(id=DWHADevelopment-Container)
title DWH A Development - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam database<<4>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam database<<5>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
package "DWH A Development\n[Software System]" {
  database "==DWH database (Project A)\n<size:10>[Container: relational database]</size>" <<5>> as 5
  database "==Repository database (Project A)\n<size:10>[Container: relational database]</size>" <<4>> as 4
}
@enduml