@startuml(id=DWHADevelopment-SystemContext)
title DWH A Development - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<3>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
rectangle "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<1>> as 1
rectangle "==DWH A Development\n<size:10>[Software System]</size>" <<3>> as 3
1 .[#707070].> 3 : "uses for testing and development"
@enduml