@startuml(id=SystemLandscape)
title System Landscape

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<11>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<3>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<4>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<5>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<10>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
rectangle "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<1>> as 1
rectangle "==DWH Developer\n<size:10>[Person]</size>\n\nDeveloper of some DWH" <<2>> as 2
rectangle "==Project A DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project A)" <<3>> as 3
rectangle "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<4>> as 4
rectangle "==MS SQL DHW\n<size:10>[Software System]</size>" <<5>> as 5
rectangle "==MS SQL Development\n<size:10>[Software System]</size>" <<10>> as 10
rectangle "==MS SQL Production\n<size:10>[Software System]</size>" <<11>> as 11
1 .[#707070].> 5 : "developes DHW in"
1 .[#707070].> 10 : "uses for testing and development"
2 .[#707070].> 10 : "developes DWH in"
2 .[#707070].> 11 : "deployes DWH to"
3 .[#707070].> 11 : "uses DWH A"
4 .[#707070].> 11 : "uses DWH B"
@enduml