@startuml(id=MSSQLDHW-Container)
title MS SQL DHW - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<6>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<9>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
package "MS SQL DHW\n[Software System]" {
  rectangle "==aaa\n<size:10>[Container]</size>" <<6>> as 6
  rectangle "==bbb\n<size:10>[Container]</size>" <<9>> as 9
}
@enduml