@startuml(id=MSSQLDHW-aaa-Component)
title MS SQL DHW - aaa - Components

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<7>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam rectangle<<8>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
package "aaa\n[Container]" {
  rectangle "==asdfg\n<size:10>[Component]</size>" <<8>> as 8
  rectangle "==qwertz\n<size:10>[Component]</size>" <<7>> as 7
}
@enduml