@startuml(id=DataHandwerkgit-SystemContext)
title DataHandwerk git - System Context

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
actor "DHW Developer" <<Person>> as 1 #dddddd
note right of 1
  Developer of DataHandwerk Toolkit
end note
actor "DWH Developer" <<Person>> as 7 #dddddd
note right of 7
  Developer of some DWH
end note
folder 6 <<Software System>> #dddddd [
  DataHandwerk git
  --
  Code of DataHandwerk unter Version Control
]
1 .[#707070].> 6 : uses
7 .[#707070].> 6 : takes code or builds
@enduml