@startuml(id=DWHBProduction-SystemContext)
title DWH B Production - System Context

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
actor "Deployment Team" <<Person>> as 8 #dddddd
actor "Project B DWH User" <<Person>> as 9 #dddddd
note right of 9
  user of DWH (Project B)
end note
rectangle 26 <<Software System>> #dddddd [
  DWH B Production
]
8 .[#707070].> 26 : deployes on production system
9 .[#707070].> 26 : uses
@enduml