@startuml(id=DataHandwerkToolkit-SystemContext)
title DataHandwerk Toolkit - System Context

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
actor "DHW Developer" <<Person>> as 1 #dddddd
note right of 1
  Developer of DataHandwerk Toolkit
end note
rectangle 2 <<Software System>> #dddddd [
  DataHandwerk Toolkit
]
1 .[#707070].> 2 : developes
@enduml