@startuml(id=DWHBDevelopment-RepositorydatabaseProjectB-Component)
title DWH B Development - Repository database (Project B) - Components

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
database 23 <<Container: relational database>> #dddddd [
  DWH database Development (Project B)
]
package "Repository database (Project B)" <<Container: relational database>> {
  rectangle 13 <<Component>> #dddddd [
    Configuration
    --
    Connection with DWH database and various settings for the behavior of the processes in the repository.
  ]
  rectangle 17 <<Component>> #dddddd [
    Inheritance
    --
    Inheritance or determination of extended properties for RepoObjects or RepoObject columns, based on references
  ]
  rectangle 19 <<Component>> #dddddd [
    Persistence Generator
    --
    Views or tables can be persisted in tables, with or without history with temporal tables. Code for performing the persistations is created.
  ]
  rectangle 16 <<Component>> #dddddd [
    Reference
    --
    Determination and management of references (dependencies) between RepoObjects or RepoObject columns
  ]
  rectangle 14 <<Component>> #dddddd [
    RepoObject
    --
    Central construct to represent objects (tables, views, procedures, functions, index, ...) and their subunits (columns, index columns, procedure parameters, ...), their properties and relationships between them.
  ]
  rectangle 15 <<Component>> #dddddd [
    SqlParser
    --
    Parse the code of views to extract column-level references or other logic from them
  ]
  rectangle 12 <<Component>> #dddddd [
    Synonyms
    --
    Synonyms are used to connect the repository database with the corresponding DWH database
  ]
  rectangle 18 <<Component>> #dddddd [
    USP Generator
    --
    usp (userdefined stored procedures) can be generated in a formalized way: containing optional logging and some workflow elements (sub procedures, conditions, parent-child logic)
  ]
  rectangle 20 <<Component>> #dddddd [
    View Generator
    --
    Not yet implemented
  ]
  rectangle 22 <<Component: ?>> #dddddd [
    Visualzation
    --
    Visualization of data lineage (references), real and virtual PK, FK-PK
  ]
  rectangle 21 <<Component>> #dddddd [
    Workflow
    --
    A workflow executes procedures in a specific and necessary order.
  ]
}
23 .[#707070].> 14 : RepoObject correspond with extended properties
17 .[#707070].> 16 
17 .[#707070].> 14 
19 .[#707070].> 16 
19 .[#707070].> 14 
19 .[#707070].> 18 
16 .[#707070].> 14 
16 .[#707070].> 15 
14 .[#707070].> 23 
14 .[#707070].> 12 
15 .[#707070].> 12 
12 .[#707070].> 23 : Synonyms link to DWH System Views
18 .[#707070].> 14 
20 .[#707070].> 14 
20 .[#707070].> 15 
22 .[#707070].> 16 
21 .[#707070].> 16 
@enduml