@startuml(id=DWHBDevelopment-SystemContext)
title DWH B Development - System Context

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
actor "DWH Developer" <<Person>> as 7 #dddddd
note right of 7
  Developer of some DWH
end note
rectangle 10 <<Software System>> #dddddd [
  DWH B Development
]
7 .[#707070].> 10 : developes
@enduml