= some cmd command

== call sqlparser

execute this in a commandline:

....
D:
cd D:\Repos\gitlab\DataHandwerk\DataHandwerk-toolkit-mssql\python\SqlParser\dist\SqlParser
SqlParser --server localhost\sql2019 --database dhw_self
....

== create dacpac containing data

how to create the dacpac of the dhw_repository containing data

https://docs.microsoft.com/de-de/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver15

....
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\sqlpackage.exe" /TargetFile:"D:\Repos\gitlab\DataHandwerk\DataHandwerk-toolkit-mssql\dhw_dacpac\dhw_self_alltabledata.dacpac" /Action:Extract /SourceServerName:"localhost\sql2019" /SourceDatabaseName:"dhw_self" /p:ExtractAllTableData=TRUE /p:IgnorePermissions=TRUE /p:IgnoreUserLoginMappings=TRUE
....

24.805 kb, can be reduced to 8.217 kb by including less tables:

....
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\sqlpackage.exe" /TargetFile:"D:\Repos\gitlab\DataHandwerk\DataHandwerk-toolkit-mssql\dhw_dacpac\dhw_self.dacpac" /Action:Extract /SourceServerName:"localhost\sql2019" /SourceDatabaseName:"dhw_self" /p:IgnorePermissions=TRUE /p:IgnoreUserLoginMappings=TRUE /p:TableData=[config].[Parameter] /p:TableData=[config].[SsasDatabasename] /p:TableData=[configT].[spt_values] /p:TableData=[property].[external_RepoObjectColumnProperty] /p:TableData=[property].[external_RepoObjectProperty] /p:TableData=[property].[RepoObjectColumnProperty] /p:TableData=[property].[RepoObjectProperty] /p:TableData=[property].[RepoSchemaProperty] /p:TableData=[reference].[additional_Reference] /p:TableData=[reference].[additional_Reference_database_T] /p:TableData=[reference].[additional_Reference_Object_T] /p:TableData=[reference].[additional_Reference_ObjectColumn_T] /p:TableData=[reference].[RepoObject_QueryPlan] /p:TableData=[reference].[RepoObject_reference_T] /p:TableData=[reference].[RepoObject_ReferenceTree] /p:TableData=[reference].[RepoObjectColumn_reference_T] /p:TableData=[reference].[RepoObjectColumnSource_virtual] /p:TableData=[reference].[RepoObjectSource_FirstResultSet] /p:TableData=[reference].[RepoObjectSource_QueryPlan] /p:TableData=[reference].[RepoObjectSource_virtual] /p:TableData=[repo].[ForeignKey_Indexes_union_T] /p:TableData=[repo].[ForeignKey_virtual] /p:TableData=[repo].[Index_ColumList_T] /p:TableData=[repo].[Index_ssas_T] /p:TableData=[repo].[Index_Settings] /p:TableData=[repo].[Index_virtual] /p:TableData=[repo].[IndexColumn_ssas_T] /p:TableData=[repo].[IndexColumn_virtual] /p:TableData=[repo].[RepoObject] /p:TableData=[repo].[RepoObject_persistence] /p:TableData=[repo].[RepoObjectColumn] /p:TableData=[repo].[RepoSchema] /p:TableData=[sqlparse].[RepoObject_SqlModules] /p:TableData=[sqlparse].[RepoObject_SqlModules_41_from_T] /p:TableData=[sqlparse].[RepoObject_SqlModules_61_SelectIdentifier_Union_T] /p:TableData=[ssas].[Measures_translation_T] /p:TableData=[ssas].[model_json] /p:TableData=[ssas].[model_json_31_tables_T] /p:TableData=[ssas].[model_json_311_tables_columns_T] /p:TableData=[ssas].[model_json_312_tables_measures_T] /p:TableData=[ssas].[model_json_32_relationships_T] /p:TableData=[ssas].[model_json_33_dataSources_T] /p:TableData=[ssas].[model_json_3411_cultures_translations_model_T] /p:TableData=[ssas].[RepoObjectColumn_translation_T] /p:TableData=[ssis].[Package] /p:TableData=[ssis].[PackageConnection] /p:TableData=[ssis].[PackageFlow] /p:TableData=[ssis].[PackageParameter] /p:TableData=[ssis].[PackageTask] /p:TableData=[ssis].[PackageTask_Dft_Component] /p:TableData=[ssis].[PackageTask_Dft_Component_input] /p:TableData=[ssis].[PackageTask_Dft_Component_input_externalMetadataColumn] /p:TableData=[ssis].[PackageTask_Dft_Component_input_inputColumn] /p:TableData=[ssis].[PackageTask_Dft_Component_output] /p:TableData=[ssis].[PackageTask_Dft_Component_output_externalMetadataColumn] /p:TableData=[ssis].[PackageTask_Dft_Component_output_outputcolumn] /p:TableData=[ssis].[PackageTask_Dft_SrcDest] /p:TableData=[ssis].[PackageTask_Sql_Parameter] /p:TableData=[ssis].[PackageVariable] /p:TableData=[ssis].[Project] /p:TableData=[ssis].[ProjectConnection] /p:TableData=[uspgenerator].[GeneratorUsp] /p:TableData=[uspgenerator].[GeneratorUspParameter] /p:TableData=[uspgenerator].[GeneratorUspStep] /p:TableData=[workflow].[Connection] /p:TableData=[workflow].[ProcedureDependency] /p:TableData=[workflow].[Workflow] /p:TableData=[workflow].[Workflow_ProcedureDependency_T] /p:TableData=[workflow].[Workflow_ProcedureDependency_T_bidirectional_T] /p:TableData=[workflow].[WorkflowStep] /p:TableData=[workflow].[WorkflowStep_Sortorder]
....

== how to create the sql examiner snapshot

[SQL Examiner](https://www.sqlaccessories.com/sql-examiner/)

....
"C:\Program Files (x86)\SQL Examiner Suite 2022\SQLECmd.exe" /server1:localhost\sql2019 /database1:dhw_self /WinAuth1 /SaveSnapshot:"D:\Repos\gitlab\DataHandwerk\DataHandwerk-toolkit-mssql\sqlexaminer\dhw.%DB1.sesnap" /force
....



////
== sript with data (don't do this, it creates too big files)

....
py -m mssqlscripter -S localhost\sql2019 -d dhw_self --schema-and-data --data-compressions -f "D:\Repos\GitHub\DataHandwerk\DataHandwerk-toolkit-mssql\mssql\script\dhw_self.sql"
....
////
