
CREATE VIEW [repo].[RepoObject_gross]
AS
--
SELECT [ro].[RepoObject_guid]
 , [ro].[RepoObject_schema_name]
 , [ro].[RepoObject_name]
 , [ro].[RepoObject_type]
 , [ro].[has_different_sys_names]
 , [ro].[has_execution_plan_issue]
 , [ro].[has_get_referenced_issue]
 , [ro].[is_repo_managed]
 , [ro].[is_RepoObject_name_uniqueidentifier]
 , [ro].[is_SysObject_missing]
 , [ro].[is_SysObject_name_uniqueidentifier]
 , [ro].[modify_dt]
 , [ro].[node_id]
 , [ro].[pk_index_guid]
 , [ro].[Repo_history_table_guid]
 , [ro].[Repo_temporal_type]
 , [ro].[RepoObject_Referencing_Count]
 , [ro].[RepoObject_fullname]
 , [ro].[SysObject_fullname]
 , [ro].[SysObject_id]
 , [ro].[SysObject_modify_date]
 , [ro].[SysObject_name]
 , [ro].[SysObject_parent_object_id]
 , [ro].[SysObject_query_executed_dt]
 , [ro].[SysObject_query_plan]
 , [ro].[SysObject_query_sql]
 , [ro].[SysObject_schema_name]
 , [ro].[SysObject_type]
 , [ro].[usp_persistence_name]
 , [rot].[source_RepoObject_guid] AS [persistence_source_RepoObject_guid]
 , [rop_s].[RepoObject_fullname] AS [persistence_source_RepoObject_fullname]
 , [rop_s].[SysObject_fullname] AS [persistence_source_SysObject_fullname]
 , [rot].[has_history]
 , [rot].[has_history_columns]
 , [rot].[is_persistence]
 , [rot].[is_persistence_check_duplicate_per_pk]
 , [rot].[is_persistence_check_for_empty_source]
 , [rot].[is_persistence_delete_missing]
 , [rot].[is_persistence_delete_changed]
 , [rot].[is_persistence_insert]
 , [rot].[is_persistence_truncate]
 , [rot].[is_persistence_update_changed]
 , [rot].[history_schema_name]
 , [rot].[history_table_name]
 , [rot].[temporal_type]
 , [ColumnList].[CreateColumnList]
 , [ColumnList].[PersistenceCompareColumnList]
 , [ColumnList].[PersistenceInsertColumnList]
 , [ColumnList].[PersistenceUpdateColumnList]
FROM repo.RepoObject AS ro
LEFT OUTER JOIN repo.RepoObject_persistence AS rot
 ON rot.target_RepoObject_guid = ro.RepoObject_guid
LEFT OUTER JOIN repo.RepoObject AS rop_s
 ON rop_s.RepoObject_guid = rot.source_RepoObject_guid
LEFT OUTER JOIN repo.RepoObject_ColumnList AS ColumnList
 ON ColumnList.RepoObject_guid = ro.RepoObject_guid
