@startuml(id=DataHandwerkgit-SystemContext)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title DataHandwerk git - System Context

Person(1, "DHW Developer", "Developer of DataHandwerk Toolkit")
Person(7, "DWH Developer", "Developer of some DWH")
System(6, "DataHandwerk git", "Code of DataHandwerk unter Version Control")
Rel_D(1, 6, "uses", "")
Rel_D(7, 6, "takes code or builds", "")
@enduml