@startuml(id=SystemLandscape)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title System Landscape

Person(1, "DHW Developer", "Developer of DataHandwerk Toolkit")
Person(7, "DWH Developer", "Developer of some DWH")
Person(8, "Deployment Team", "")
Person(9, "Project B DWH User", "user of DWH (Project B)")
System(3, "DWH A Development", "")
System(10, "DWH B Development", "")
System(26, "DWH B Production", "")
System(28, "DWH B git", "Code of Project B unter Version Control (git, subversion, ...)")
System(2, "DataHandwerk Toolkit", "")
System(6, "DataHandwerk git", "Code of DataHandwerk unter Version Control")
Rel_D(1, 3, "uses for testing and development", "")
Rel_D(1, 2, "developes", "")
Rel_D(1, 6, "uses", "")
Rel_D(7, 10, "developes", "")
Rel_D(7, 28, "uses", "")
Rel_D(7, 6, "takes code or builds", "")
Rel_D(8, 26, "deployes on production system", "")
Rel_D(8, 28, "takes code or builds", "")
Rel_D(9, 26, "uses", "")
@enduml