@startuml(id=DWHADevelopment-SystemContext)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title DWH A Development - System Context

Person(1, "DHW Developer", "Developer of DataHandwerk Toolkit")
System(3, "DWH A Development", "")
Rel_D(1, 3, "uses for testing and development", "")
@enduml