@startuml(id=DWHBDevelopment-Container)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title DWH B Development - Containers

System_Boundary(10_boundary, DWH B Development) {
  Container(23, "DWH database Development (Project B)", "relational database", "")
  Container(11, "Repository database (Project B)", "relational database", "")
}
Rel_D(23, 11, "RepoObject correspond with extended properties", "")
Rel_D(11, 23, "Synonyms link to DWH System Views", "")
@enduml