/*****START OF DEBUG INFORMATION*****

The primary key column list:
[index_guid]

The INSERT column list:
[index_guid],[IndexPatternColumnDatatype],[IndexPatternColumnName],[IndexSemanticGroup],[is_create_constraint]

The UPDATE column list:
 [Target].[IndexPatternColumnDatatype] = [Source].[IndexPatternColumnDatatype], 
  [Target].[IndexPatternColumnName] = [Source].[IndexPatternColumnName], 
  [Target].[IndexSemanticGroup] = [Source].[IndexSemanticGroup], 
  [Target].[is_create_constraint] = [Source].[is_create_constraint]

The SELECT statement executed to generate the MERGE:
SELECT ' ' + CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) = 1 THEN ' ' ELSE ',' END + '('+ COALESCE('N''' + REPLACE(CONVERT(char(36),RTRIM([index_guid])),'''','''''')+'''','NULL')+',' + COALESCE('N''' + REPLACE([IndexPatternColumnDatatype],'''','''''')+'''','NULL')+',' + COALESCE('N''' + REPLACE([IndexPatternColumnName],'''','''''')+'''','NULL')+',' + COALESCE('N''' + REPLACE([IndexSemanticGroup],'''','''''')+'''','NULL')+',' + COALESCE(LTRIM(RTRIM(CONVERT(char, [is_create_constraint]))),'NULL')+')'  FROM [repo].[Index_Settings] (NOLOCK) ORDER BY [index_guid]

*****END OF DEBUG INFORMATION*****/


USE [dhw_self]
GO

--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

MERGE INTO [repo].[Index_Settings] AS [Target]
USING (VALUES
  (N'ED8F291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'EF8F291C-9D61-EB11-84DC-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'SysObject_schema_name;SysObject_name',N'schema_name;object_name',0)
 ,(N'F18F291C-9D61-EB11-84DC-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'RepoObject_schema_name;RepoObject_name',N'schema_name;object_name',0)
 ,(N'1290291C-9D61-EB11-84DC-A81E8446D5B0',N'int',N'RepoObjectProperty_id',N'RepoObjectProperty_id',0)
 ,(N'1490291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObject_guid;property_name',NULL,0)
 ,(N'1890291C-9D61-EB11-84DC-A81E8446D5B0',N'int',N'RepoObjectColumnProperty_id',N'RepoObjectColumnProperty_id',0)
 ,(N'1A90291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObjectColumn_guid;property_name',NULL,0)
 ,(N'1E90291C-9D61-EB11-84DC-A81E8446D5B0',N'bigint',N'id',N'ExecutionLog_id',0)
 ,(N'2290291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'index_guid',N'index_guid',0)
 ,(N'2690291C-9D61-EB11-84DC-A81E8446D5B0',N'varchar(100);nvarchar(128)',N'Parameter_name;sub_Parameter',N'Parameter_name;sub_Parameter',0)
 ,(N'2A90291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'2E90291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;int',N'RepoObject_guid;column_ordinal',NULL,0)
 ,(N'3690291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'index_guid',N'index_guid',0)
 ,(N'3A90291C-9D61-EB11-84DC-A81E8446D5B0',N'int',N'id',N'usp_id',0)
 ,(N'3C90291C-9D61-EB11-84DC-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'usp_schema;usp_name',N'usp_schema;usp_name',0)
 ,(N'4090291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'4290291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObjectColumn_guid;SysObjectColumn_name',N'RepoObjectColumn_guid;SysObjectColumn_name',0)
 ,(N'4490291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObject_guid;RepoObjectColumn_name',N'RepoObject_guid;Column_name',0)
 ,(N'4890291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'target_RepoObject_guid',N'RepoObjectColumn_guid',0)
 ,(N'4C90291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;int',N'index_guid;index_column_id',N'index_guid;index_column_id',0)
 ,(N'5090291C-9D61-EB11-84DC-A81E8446D5B0',N'int',N'id',N'UspParameter_id',0)
 ,(N'5290291C-9D61-EB11-84DC-A81E8446D5B0',N'int;int',N'usp_id;Number',N'usp_id;Number',0)
 ,(N'5490291C-9D61-EB11-84DC-A81E8446D5B0',N'int;nvarchar(128)',N'usp_id;Name',N'usp_id;Name',0)
 ,(N'5890291C-9D61-EB11-84DC-A81E8446D5B0',N'int',N'id',N'UspStep_id',0)
 ,(N'5A90291C-9D61-EB11-84DC-A81E8446D5B0',N'int;int',N'usp_id;Number',N'usp_id;Number',0)
 ,(N'C090291C-9D61-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'OperationKey',NULL,0)
 ,(N'63CE8EB8-5F62-EB11-84DC-A81E8446D5B0',N'int',N'diagram_id',NULL,0)
 ,(N'64CE8EB8-5F62-EB11-84DC-A81E8446D5B0',N'int;sysname',N'principal_id;name',NULL,0)
 ,(N'8519C175-6962-EB11-84DC-A81E8446D5B0',N'bigint',N'id',N'ExecutionLog_id',0)
 ,(N'8D19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'8E19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'9019C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'9319C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'index_guid',N'index_guid',0)
 ,(N'9419C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'index_guid',N'index_guid',0)
 ,(N'9519C175-6962-EB11-84DC-A81E8446D5B0',N'int',N'id',N'usp_id',0)
 ,(N'9819C175-6962-EB11-84DC-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'usp_schema;usp_name',N'usp_schema;usp_name',0)
 ,(N'9919C175-6962-EB11-84DC-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'usp_schema;usp_name',N'usp_schema;usp_name',0)
 ,(N'9C19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'referencing_RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'9D19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'referenced_RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'A019C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'A319C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'A419C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'A619C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'referenced_RepoObjectColumn_guid;referencing_column_name',N'RepoObjectColumn_guid;SysObjectColumn_name',0)
 ,(N'A719C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'referencing_RepoObjectColumn_guid;referenced_column_name',N'RepoObjectColumn_guid;SysObjectColumn_name',0)
 ,(N'AD19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObjectColumn_guid;SysObjectColumn_name',N'RepoObjectColumn_guid;SysObjectColumn_name',0)
 ,(N'AE19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObjectColumn_guid;SysObjectColumn_name',N'RepoObjectColumn_guid;SysObjectColumn_name',0)
 ,(N'BB19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObject_guid;RepoObjectColumn_name',N'RepoObject_guid;Column_name',0)
 ,(N'BC19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObject_guid;RepoObjectColumn_name',N'RepoObject_guid;Column_name',0)
 ,(N'C519C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'referencing_RepoObject_guid',N'RepoObjectColumn_guid',0)
 ,(N'C619C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'referencing_RepoObject_guid',N'RepoObjectColumn_guid',0)
 ,(N'C719C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'target_RepoObject_guid',N'RepoObjectColumn_guid',0)
 ,(N'C819C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'target_RepoObject_guid',N'RepoObjectColumn_guid',0)
 ,(N'CA19C175-6962-EB11-84DC-A81E8446D5B0',N'uniqueidentifier;int',N'index_guid;index_column_id',N'index_guid;index_column_id',0)
 ,(N'EFCE9178-6B62-EB11-84DC-A81E8446D5B0',N'uniqueidentifier',N'index_guid',N'index_guid',0)
 ,(N'D9427A38-4265-EB11-84DD-A81E8446D5B0',N'nvarchar(128)',N'RepoObjectColumn_name',NULL,0)
 ,(N'DA427A38-4265-EB11-84DD-A81E8446D5B0',N'nvarchar(128)',N'source_RepoObjectColumn_name',NULL,0)
 ,(N'DB427A38-4265-EB11-84DD-A81E8446D5B0',N'nvarchar(128)',N'source_RepoObjectColumn_name',NULL,0)
 ,(N'DC427A38-4265-EB11-84DD-A81E8446D5B0',N'nvarchar(128)',N'RepoObjectColumn_name',NULL,0)
 ,(N'DF427A38-4265-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'E0427A38-4265-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'source_RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'E3427A38-4265-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'source_RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'E4427A38-4265-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'E7427A38-4265-EB11-84DD-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObject_guid;RepoObjectColumn_name',N'RepoObject_guid;Column_name',0)
 ,(N'EC427A38-4265-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObjectColumn_guid',N'RepoObjectColumn_guid',0)
 ,(N'EF427A38-4265-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'target_RepoObject_guid',N'RepoObjectColumn_guid',0)
 ,(N'4EC2589C-5265-EB11-84DD-A81E8446D5B0',N'uniqueidentifier;nvarchar(128)',N'RepoObject_guid;RepoObjectColumn_name',N'RepoObject_guid;Column_name',0)
 ,(N'6E34CB25-1E66-EB11-84DD-A81E8446D5B0',N'int',N'id',N'WorkflowStep_id',0)
 ,(N'6F34CB25-1E66-EB11-84DD-A81E8446D5B0',N'int;int',N'Workflow_id;ProcedureInstance_id',NULL,0)
 ,(N'7034CB25-1E66-EB11-84DD-A81E8446D5B0',N'int',N'id',N'Workflow_id',0)
 ,(N'7734CB25-1E66-EB11-84DD-A81E8446D5B0',N'int',N'id',N'ProcedureInstance_id',0)
 ,(N'7834CB25-1E66-EB11-84DD-A81E8446D5B0',N'uniqueidentifier;varchar(500)',N'Procedure_RepoObject_guid;Instance',N'ProcedureInstance_UK',0)
 ,(N'7C34CB25-1E66-EB11-84DD-A81E8446D5B0',N'int',N'id',N'ProcedureInstanceDependency_id',0)
 ,(N'7D34CB25-1E66-EB11-84DD-A81E8446D5B0',N'int;int',N'referenced_id;referencing_id',NULL,0)
 ,(N'2BC1E60F-ED66-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',NULL,0)
 ,(N'2CC1E60F-ED66-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObjectColumn_guid',NULL,0)
 ,(N'2DC1E60F-ED66-EB11-84DD-A81E8446D5B0',N'uniqueidentifier;varchar(500)',N'Procedure_RepoObject_guid;Instance',N'ProcedureInstance_UK',0)
 ,(N'166B6592-EF66-EB11-84DD-A81E8446D5B0',N'uniqueidentifier;varchar(500)',N'Procedure_RepoObject_guid;Instance',N'ProcedureInstance_UK',0)
 ,(N'1D6B6592-EF66-EB11-84DD-A81E8446D5B0',N'nvarchar(128)',N'referencing_column_name',NULL,0)
 ,(N'1E6B6592-EF66-EB11-84DD-A81E8446D5B0',N'nvarchar(128)',N'referenced_column_name',NULL,0)
 ,(N'A7C621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'A8C621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'source_RepoObject_guid',N'RepoObject_guid',0)
 ,(N'A9C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'SysObject_schema_name;SysObject_name',N'schema_name;object_name',0)
 ,(N'ABC621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'ADC621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'RepoObject_schema_name;RepoObject_name',N'schema_name;object_name',0)
 ,(N'AFC621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'B4C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'RepoObject_schema_name;RepoObject_name',N'schema_name;object_name',0)
 ,(N'B8C621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'BAC621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'source_RepoObject_guid',N'RepoObject_guid',0)
 ,(N'BBC621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'BCC621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'SysObject_schema_name;SysObject_name',N'schema_name;object_name',0)
 ,(N'BEC621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'RepoObject_schema_name;RepoObject_name',N'schema_name;object_name',0)
 ,(N'C0C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'SysObject_schema_name;SysObject_name',N'schema_name;object_name',0)
 ,(N'C2C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'parent_schema_name;parent_SysObject_name',N'schema_name;object_name',0)
 ,(N'C4C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'RepoObject_schema_name;RepoObject_name',N'schema_name;object_name',0)
 ,(N'C6C621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'parent_RepoObject_guid',N'RepoObject_guid',0)
 ,(N'C7C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'referencing_schema_name;referenced_entity_name',N'schema_name;object_name',0)
 ,(N'C8C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'referenced_schema_name;referencing_entity_name',N'schema_name;object_name',0)
 ,(N'CBC621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'CCC621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'SysObject_schema_name;SysObject_name',N'schema_name;object_name',0)
 ,(N'CEC621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128)',N'SysObject_name',NULL,0)
 ,(N'CFC621A8-0867-EB11-84DD-A81E8446D5B0',N'sysname;sysname',N'SysObject_schema_name;SysObject_name',NULL,0)
 ,(N'D1C621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'D3C621A8-0867-EB11-84DD-A81E8446D5B0',N'sysname;sysname',N'SysObject_schema_name;SysObject_name',NULL,0)
 ,(N'D5C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'referenced_schema_name;referencing_entity_name',N'schema_name;object_name',0)
 ,(N'D6C621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'referencing_schema_name;referenced_entity_name',N'schema_name;object_name',0)
 ,(N'D9C621A8-0867-EB11-84DD-A81E8446D5B0',N'uniqueidentifier',N'RepoObject_guid',N'RepoObject_guid',0)
 ,(N'DBC621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'RepoObject_schema_name;RepoObject_name',N'schema_name;object_name',0)
 ,(N'DDC621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'referencing_schema_name;referenced_entity_name',N'schema_name;object_name',0)
 ,(N'DEC621A8-0867-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'referenced_schema_name;referencing_entity_name',N'schema_name;object_name',0)
 ,(N'ADB7BA42-0B67-EB11-84DD-A81E8446D5B0',N'nvarchar(128);nvarchar(128)',N'SysObject_schema_name;SysObject_name',N'schema_name;object_name',0)
 ,(N'432CC058-426D-EB11-84E2-A81E8446D5B0',N'uniqueidentifier;varchar(500)',N'Procedure_RepoObject_guid;Instance',N'ProcedureInstance_UK',0)
 ,(N'442CC058-426D-EB11-84E2-A81E8446D5B0',N'uniqueidentifier;varchar(500)',N'Procedure_RepoObject_guid;Instance',N'ProcedureInstance_UK',0)
) AS [Source] ([index_guid],[IndexPatternColumnDatatype],[IndexPatternColumnName],[IndexSemanticGroup],[is_create_constraint])
ON ([Target].[index_guid] = [Source].[index_guid])
WHEN MATCHED AND (
	NULLIF([Source].[IndexPatternColumnDatatype], [Target].[IndexPatternColumnDatatype]) IS NOT NULL OR NULLIF([Target].[IndexPatternColumnDatatype], [Source].[IndexPatternColumnDatatype]) IS NOT NULL OR 
	NULLIF([Source].[IndexPatternColumnName], [Target].[IndexPatternColumnName]) IS NOT NULL OR NULLIF([Target].[IndexPatternColumnName], [Source].[IndexPatternColumnName]) IS NOT NULL OR 
	NULLIF([Source].[IndexSemanticGroup], [Target].[IndexSemanticGroup]) IS NOT NULL OR NULLIF([Target].[IndexSemanticGroup], [Source].[IndexSemanticGroup]) IS NOT NULL OR 
	NULLIF([Source].[is_create_constraint], [Target].[is_create_constraint]) IS NOT NULL OR NULLIF([Target].[is_create_constraint], [Source].[is_create_constraint]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[IndexPatternColumnDatatype] = [Source].[IndexPatternColumnDatatype], 
  [Target].[IndexPatternColumnName] = [Source].[IndexPatternColumnName], 
  [Target].[IndexSemanticGroup] = [Source].[IndexSemanticGroup], 
  [Target].[is_create_constraint] = [Source].[is_create_constraint]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([index_guid],[IndexPatternColumnDatatype],[IndexPatternColumnName],[IndexSemanticGroup],[is_create_constraint])
 VALUES([Source].[index_guid],[Source].[IndexPatternColumnDatatype],[Source].[IndexPatternColumnName],[Source].[IndexSemanticGroup],[Source].[is_create_constraint])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [repo].[Index_Settings]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[repo].[Index_Settings] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO


SET NOCOUNT OFF
GO
