graph TB
  linkStyle default fill:#ffffff
  7["<div style='font-weight: bold'>Deployment Team</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'></div>"]
  style 7 fill:#dddddd,stroke:#9a9a9a,color:#000000
  8["<div style='font-weight: bold'>Project B DWH User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>user of DWH (Project B)</div>"]
  style 8 fill:#dddddd,stroke:#9a9a9a,color:#000000
  subgraph boundary [DWH B Production]
    26[("<div style='font-weight: bold'>DWH database Production (Project B)</div><div style='font-size: 70%; margin-top: 0px'>[Container: Database]</div><div style='font-size: 80%; margin-top:10px'></div>")]
    style 26 fill:#dddddd,stroke:#9a9a9a,color:#000000
  end
  style boundary fill:#ffffff,stroke:#000000,color:#000000
  7-. "<div>deployes on production system</div><div style='font-size: 70%'></div>" .->26
  8-. "<div>uses</div><div style='font-size: 70%'></div>" .->26
