graph TB
  linkStyle default fill:#ffffff
  10[("<div style='font-weight: bold'>Repository database (Project B)</div><div style='font-size: 70%; margin-top: 0px'>[Container: Database]</div><div style='font-size: 80%; margin-top:10px'></div>")]
  style 10 fill:#dddddd,stroke:#9a9a9a,color:#000000
  subgraph boundary [DWH database Development (Project B)]
    24["<div style='font-weight: bold'>Extended Properties</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'></div>"]
    style 24 fill:#dddddd,stroke:#9a9a9a,color:#000000
    23["<div style='font-weight: bold'>System views and procedures</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'></div>"]
    style 23 fill:#dddddd,stroke:#9a9a9a,color:#000000
  end
  style boundary fill:#ffffff,stroke:#000000,color:#000000
  24-. "<div>RepoObject correspond with<br />extended properties</div><div style='font-size: 70%'></div>" .->10
  10-. "<div>Synonyms link to DWH System<br />Views</div><div style='font-size: 70%'></div>" .->24
