graph TB
  linkStyle default fill:#ffffff
  6["<div style='font-weight: bold'>DWH Developer</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Developer of some DWH</div>"]
  style 6 fill:#dddddd,stroke:#9a9a9a,color:#000000
  7["<div style='font-weight: bold'>Deployment Team</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'></div>"]
  style 7 fill:#dddddd,stroke:#9a9a9a,color:#000000
  27["<div style='font-weight: bold'>DWH B git</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Code of Project B unter<br />Version Control (git,<br />subversion, ...)</div>"]
  style 27 fill:#dddddd,stroke:#9a9a9a,color:#000000
  6-. "<div>uses</div><div style='font-size: 70%'></div>" .->27
  7-. "<div>takes code or builds</div><div style='font-size: 70%'></div>" .->27
