graph TB
  linkStyle default fill:#ffffff
  22[("<div style='font-weight: bold'>DWH database Development (Project B)</div><div style='font-size: 70%; margin-top: 0px'>[Container: Database]</div><div style='font-size: 80%; margin-top:10px'></div>")]
  style 22 fill:#dddddd,stroke:#9a9a9a,color:#000000
  subgraph boundary [Repository database (Project B)]
    12["<div style='font-weight: bold'>Configuration</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Connection with DWH database<br />and various settings for the<br />behavior of the processes in<br />the repository.</div>"]
    style 12 fill:#dddddd,stroke:#9a9a9a,color:#000000
    16["<div style='font-weight: bold'>Inheritance</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Inheritance or determination<br />of extended properties for<br />RepoObjects or RepoObject<br />columns, based on references</div>"]
    style 16 fill:#dddddd,stroke:#9a9a9a,color:#000000
    18["<div style='font-weight: bold'>Persistence Generator</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Views or tables can be<br />persisted in tables, with or<br />without history with temporal<br />tables. Code for performing<br />the persistations is created.</div>"]
    style 18 fill:#dddddd,stroke:#9a9a9a,color:#000000
    15["<div style='font-weight: bold'>Reference</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Determination and management<br />of references (dependencies)<br />between RepoObjects or<br />RepoObject columns</div>"]
    style 15 fill:#dddddd,stroke:#9a9a9a,color:#000000
    13["<div style='font-weight: bold'>RepoObject</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Central construct to<br />represent objects (tables,<br />views, procedures, functions,<br />index, ...) and their<br />subunits (columns, index<br />columns, procedure<br />parameters, ...), their<br />properties and relationships<br />between them.</div>"]
    style 13 fill:#dddddd,stroke:#9a9a9a,color:#000000
    14["<div style='font-weight: bold'>SqlParser</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Parse the code of views to<br />extract column-level<br />references or other logic<br />from them</div>"]
    style 14 fill:#dddddd,stroke:#9a9a9a,color:#000000
    11["<div style='font-weight: bold'>Synonyms</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Synonyms are used to connect<br />the repository database with<br />the corresponding DWH<br />database</div>"]
    style 11 fill:#dddddd,stroke:#9a9a9a,color:#000000
    17["<div style='font-weight: bold'>USP Generator</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>usp (userdefined stored<br />procedures) can be generated<br />in a formalized way:<br />containing optional logging<br />and some workflow elements<br />(sub procedures, conditions,<br />parent-child logic)</div>"]
    style 17 fill:#dddddd,stroke:#9a9a9a,color:#000000
    19["<div style='font-weight: bold'>View Generator</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>Not yet implemented</div>"]
    style 19 fill:#dddddd,stroke:#9a9a9a,color:#000000
    21["<div style='font-weight: bold'>Visualzation</div><div style='font-size: 70%; margin-top: 0px'>[Component: ?]</div><div style='font-size: 80%; margin-top:10px'>Visualization of data lineage<br />(references), real and<br />virtual PK, FK-PK</div>"]
    style 21 fill:#dddddd,stroke:#9a9a9a,color:#000000
    20["<div style='font-weight: bold'>Workflow</div><div style='font-size: 70%; margin-top: 0px'>[Component]</div><div style='font-size: 80%; margin-top:10px'>A workflow executes<br />procedures in a specific and<br />necessary order.</div>"]
    style 20 fill:#dddddd,stroke:#9a9a9a,color:#000000
  end
  style boundary fill:#ffffff,stroke:#000000,color:#000000
  22-. "<div>RepoObject correspond with<br />extended properties</div><div style='font-size: 70%'></div>" .->13
  16-. "<div></div><div style='font-size: 70%'></div>" .->15
  16-. "<div></div><div style='font-size: 70%'></div>" .->13
  18-. "<div></div><div style='font-size: 70%'></div>" .->15
  18-. "<div></div><div style='font-size: 70%'></div>" .->13
  18-. "<div></div><div style='font-size: 70%'></div>" .->17
  15-. "<div></div><div style='font-size: 70%'></div>" .->13
  15-. "<div></div><div style='font-size: 70%'></div>" .->14
  13-. "<div></div><div style='font-size: 70%'></div>" .->22
  13-. "<div></div><div style='font-size: 70%'></div>" .->11
  14-. "<div></div><div style='font-size: 70%'></div>" .->11
  11-. "<div>Synonyms link to DWH System<br />Views</div><div style='font-size: 70%'></div>" .->22
  17-. "<div></div><div style='font-size: 70%'></div>" .->13
  19-. "<div></div><div style='font-size: 70%'></div>" .->13
  19-. "<div></div><div style='font-size: 70%'></div>" .->14
  21-. "<div></div><div style='font-size: 70%'></div>" .->15
  20-. "<div></div><div style='font-size: 70%'></div>" .->15
