graph TB
  linkStyle default fill:#ffffff
  1["<div style='font-weight: bold'>DHW Developer</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Developer of DataHandwerk<br />Toolkit</div>"]
  style 1 fill:#dddddd,stroke:#9a9a9a,color:#000000
  6["<div style='font-weight: bold'>DWH Developer</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Developer of some DWH</div>"]
  style 6 fill:#dddddd,stroke:#9a9a9a,color:#000000
  5["<div style='font-weight: bold'>DataHandwerk git</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Code of DataHandwerk unter<br />Version Control</div>"]
  style 5 fill:#dddddd,stroke:#9a9a9a,color:#000000
  1-. "<div>uses</div><div style='font-size: 70%'></div>" .->5
  6-. "<div>takes code or builds</div><div style='font-size: 70%'></div>" .->5
