graph TB
  linkStyle default fill:#ffffff
  subgraph boundary [DataHandwerk Development]
    4[("<div style='font-weight: bold'>DWH database (Project A)</div><div style='font-size: 70%; margin-top: 0px'>[Container: Database]</div><div style='font-size: 80%; margin-top:10px'></div>")]
    style 4 fill:#dddddd,stroke:#9a9a9a,color:#000000
    3[("<div style='font-weight: bold'>Repository database (Project A)</div><div style='font-size: 70%; margin-top: 0px'>[Container: Database]</div><div style='font-size: 80%; margin-top:10px'></div>")]
    style 3 fill:#dddddd,stroke:#9a9a9a,color:#000000
  end
  style boundary fill:#ffffff,stroke:#000000,color:#000000
