graph TB
  linkStyle default fill:#ffffff
  1["<div style='font-weight: bold'>DHW Developer</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Developer of DataHandwerk<br />Toolkit</div>"]
  style 1 fill:#dddddd,stroke:#9a9a9a,color:#000000
  6["<div style='font-weight: bold'>DWH Developer</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Developer of some DWH</div>"]
  style 6 fill:#dddddd,stroke:#9a9a9a,color:#000000
  7["<div style='font-weight: bold'>Deployment Team</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'></div>"]
  style 7 fill:#dddddd,stroke:#9a9a9a,color:#000000
  8["<div style='font-weight: bold'>Project B DWH User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>user of DWH (Project B)</div>"]
  style 8 fill:#dddddd,stroke:#9a9a9a,color:#000000
  9["<div style='font-weight: bold'>DWH B Development</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'></div>"]
  style 9 fill:#dddddd,stroke:#9a9a9a,color:#000000
  25["<div style='font-weight: bold'>DWH B Production</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'></div>"]
  style 25 fill:#dddddd,stroke:#9a9a9a,color:#000000
  27["<div style='font-weight: bold'>DWH B git</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Code of Project B unter<br />Version Control (git,<br />subversion, ...)</div>"]
  style 27 fill:#dddddd,stroke:#9a9a9a,color:#000000
  2["<div style='font-weight: bold'>DataHandwerk Development</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'></div>"]
  style 2 fill:#dddddd,stroke:#9a9a9a,color:#000000
  5["<div style='font-weight: bold'>DataHandwerk git</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Code of DataHandwerk unter<br />Version Control</div>"]
  style 5 fill:#dddddd,stroke:#9a9a9a,color:#000000
  1-. "<div>uses for testing and<br />development</div><div style='font-size: 70%'></div>" .->2
  1-. "<div>uses</div><div style='font-size: 70%'></div>" .->5
  6-. "<div>developes</div><div style='font-size: 70%'></div>" .->9
  6-. "<div>uses</div><div style='font-size: 70%'></div>" .->27
  6-. "<div>takes code or builds</div><div style='font-size: 70%'></div>" .->5
  7-. "<div>deployes on production system</div><div style='font-size: 70%'></div>" .->25
  7-. "<div>takes code or builds</div><div style='font-size: 70%'></div>" .->27
  8-. "<div>uses</div><div style='font-size: 70%'></div>" .->25
